# Enable debug info in console
debug-mode: false

# Enable colors in console output
color-logs: true

# Allow instanced worlds.
# Enable this to make pushable blocks placed in a template world work in the instanced worlds.
# Compatible name scheme: worldname.instance
allow-instanced-worlds: true
